movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("webapp.urls"))

]


if settings. DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieproject/webapp/urls.py
from django.urls import path
from. import views
app_name='webapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

movieproject/webapp/models.py
from django.db import models

# Create your models here.

class Movie(models.Model):
    name= models.CharField(max_length=250)
    desc= models.TextField()
    year= models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/webapp/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movieproject/webapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Movie
from.forms import MovieForm

# Create your views here.

def index(request):
    movie = Movie.objects.all()
    context = {'movie_list':movie}
    return render(request,'index.html',context)

def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})

def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc=request.POST.get('desc',)
        year=request.POST.get('year',)
        img=request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()

    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=="POST":
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST"  enctype="multipart/form-data">
   {% csrf_token %}
   <input type="text" name="name" placeholder="enter your movie name"><br>
   <input type="text" name="desc" placeholder="enter your movie desc"><br>
   <input type="text" name="year" placeholder="enter your movie year"><br>
   <input type="file" name="img"><br>
   <input type="submit">

</form>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body><!-- Image and text -->
<nav class="navbar navbar-light bg-dark">
  <a class="navbar-brand" href="#" style="color:white; text-align:center;">
    Online Movie Store
  </a>
</nav>

<h1>welcome</h1><br>

{% block body %}
{% endblock %}

<style>
    h1{width:100%; text-align:center; font-size:45px;padding:10px;}
    button{margin-left:15%; height:40px; width:120px; border:2px solid white;font-weight:bold;  border-radius:7px;}
    .btn{height:40px; width:120px;}
    .c{width:100%; height:500px; display:flex; flex-direction:column; justify-content:center;align-items:center;}
    li{list-style:none; font-size:23px; margin-left:15%; padding:5px;}
</style>
</body>
</html>

movieproject/templates/delete.html
<form method="POST">
  {% csrf_token %}
  Are you want to delete this movie?
  <button>submit</button>
</form>

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container" >
    <div class="row">
        <div class="col-md-6" >
            <img src="{{movie.img.url}}" width="300" height="300"><br>
        </div>
    </div>
</div>
<div class="col-md-6">
        <h2><li>{{movie.name}}</li></h2>
        <h4><li>{{movie.desc}}</li></h4>
        <h6><li>{{movie.year}}</li></h6>
         <button><a class="btn btn-warning" href="{% url 'webapp:update' movie.id %}">UPDATE</a></button>
         <button><a class="btn btn-danger" href="{% url 'webapp:delete' movie.id %}">DELETE</a></button>
</div>
{% endblock %}

movieproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3" style="display:flex; ">
            <div class="card" style="width: 18rem; ">
            <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" style="padding:5px;">
            <div class="card-body">
            <h5 class="card-title">{{i.name}}</h5>
           <p class="card-tdext">{{i.desc}}</p>
          <a href="{% url 'webapp:detail' i.id %}" class="btn btn-primary">Go details</a>
       </div>
       </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}